(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const n of e)if(n.type==="childList")for(const s of n.addedNodes)s.tagName==="LINK"&&s.rel==="modulepreload"&&a(s)}).observe(document,{childList:!0,subtree:!0});function r(e){const n={};return e.integrity&&(n.integrity=e.integrity),e.referrerPolicy&&(n.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?n.credentials="include":e.crossOrigin==="anonymous"?n.credentials="omit":n.credentials="same-origin",n}function a(e){if(e.ep)return;e.ep=!0;const n=r(e);fetch(e.href,n)}})();const m=axios.create({baseURL:"https://6971cf4a32c6bacb12c49096.mockapi.io"});let u=1,w="",B="asc";const M=document.querySelector("#root"),k=document.createElement("h1"),y=document.createElement("div");y.style.display="flex";y.style.justifyContent="space-between";M.append(y);const v="2px solid black",L="20px",p=document.createElement("div");p.style.border=v;p.style.padding=L;y.append(p);p.append(k);const E=document.createElement("select");E.style.marginBottom="5px";E.innerHTML="<option value='asc'>From A to Z</option><option value='desc'>From Z to A</option>";const C=document.createElement("form");C.innerHTML="<input class='search' type=text name='search' style='margin-right: 5px'><button>Search</button>";const x=document.createElement("ul");p.append(x);x.before(C);C.before(E);const h=document.createElement("div");h.style.marginBottom="5px";p.append(h);const D=document.createElement("button");D.textContent="Add Book";p.append(D);const i=document.createElement("div");i.style.maxWidth="50%";y.append(i);const c=document.createElement("div");async function l(){try{x.innerHTML="",k.textContent="LOADING...";const{data:t}=await m("/books",{params:{page:u,limit:5,search:w,sortBy:"title",order:B}});t.forEach(a=>{const e=document.createElement("li");e.id=a.id,e.style.marginBottom="10px";const n=a.title+" ",s=document.createElement("button");s.textContent="View Details",s.style.marginRight="5px",s.addEventListener("click",b=>{S(b)});const d=document.createElement("button");d.textContent="Delete book",d.style.marginRight="5px",d.addEventListener("click",b=>N(b));const f=document.createElement("button");f.textContent="Edit book",f.addEventListener("click",b=>A(b)),e.append(n,s,d,f),x.appendChild(e)}),h.innerHTML=`
    <button class="prev">&lt;</button>
    <strong> ${u} </strong>
    <button class="next">&gt;</button>`;const o=h.querySelector(".prev"),r=h.querySelector(".next");o.addEventListener("click",F),r.addEventListener("click",q),u===1&&(o.style.display="none"),t.length<5&&(r.style.display="none")}catch(t){console.log(t)}finally{k.textContent="Список книг"}}async function S(t){i.innerHTML="",i.style.border=v,i.style.padding=L;const o=t.target.parentNode.id,r=t.target;r.textContent="Loading...";try{const{data:a}=await m(`/books/${o}`);i.innerHTML=`
        <h2>${a.title}</h2>
        <p><strong>Автор:</strong> ${a.author}</p>
        <p><strong>Рік видання:</strong> ${a.year}</p>
        <p><strong>Опис:</strong> ${a.description}</p>
      `}catch(a){console.log(a)}finally{r.textContent="View Details"}}async function N(t){const o=t.target.parentNode.id;try{t.target.textContent="Deleteing...",await m.delete(`/books/${o}`),l(),O()}catch(r){console.log(r)}finally{t.target.textContent="Delete book"}}function O(){c.innerHTML="",g(i),setTimeout(()=>{c.innerHTML="<strong>Книгу успішно видалено!</strong>",c.style.width="25%",c.style.textAlign="center",c.style.padding=L,c.style.border=v,y.append(c)},1e3),setTimeout(()=>{c.remove()},3e3)}function T(){const t=document.createElement("form");return t.style.display="flex",t.style.flexDirection="column",t.style.gap="30px",t.innerHTML=`
    <label>Title <input name="title"></label>
    <label>Author <input name="author"></label>
    <label>Year <input name="year"></label>
    <label>Description <textarea name="desc" rows="5" cols="40"></textarea></label>
    <button type="submit">Submit</button>
  `,t}function H(t){return Object.values(t).some(o=>o===null||o.trim()==="")?(alert("Поля не мають бути пустими!"),!1):Number.isInteger(Number(t.year))?!0:(alert("Рік має бути числом"),!1)}function $(){i.innerHTML="";const t=document.createElement("h2");t.textContent="Додати книгу",i.prepend(t);const o=T();o.addEventListener("submit",async r=>{r.preventDefault();const a=new FormData(r.target),e={title:a.get("title"),author:a.get("author"),year:a.get("year"),description:a.get("desc")};if(H(e)){const n=o.querySelector("button");n.textContent="Submiting...";try{await m.post("/books",e),l(),g(i)}catch(s){console.log(s)}finally{n.textContent="Submit"}}}),i.append(o)}async function A(t){i.innerHTML="",i.style.border=v,i.style.padding=L;const o=document.createElement("h2");o.textContent="Редагувати книгу",i.prepend(o);const r=T(),a=t.target.parentNode.id;try{const{data:e}=await m(`/books/${a}`);r.elements.title.value=e.title,r.elements.author.value=e.author,r.elements.year.value=e.year,r.elements.desc.value=e.description}catch(e){console.log(e)}r.addEventListener("submit",async e=>{e.preventDefault();const n=new FormData(e.target),s={title:n.get("title"),author:n.get("author"),year:n.get("year"),description:n.get("desc")};if(H(s)){const d=r.querySelector("button");d.textContent="Submiting...";try{await m.put(`/books/${a}`,s),l(),g(i)}catch(f){console.log(f)}finally{d.textContent="Submit"}}}),i.append(r)}function F(){g(i),u-=1,l()}function q(){g(i),u+=1,l()}function g(t){t.innerHTML="",t.style.border="none"}function P(t){t.preventDefault(),w=t.target.elements.search.value.trim(),u=1,l(),t.target.reset(),g(i)}function I(t){B=t.target.value,u=1,l()}D.addEventListener("click",$);l();C.addEventListener("submit",P);E.addEventListener("change",I);
//# sourceMappingURL=index.js.map
